Repository tensorflow/tfjs-layers, pull requests merged in 2019-03, with the labels that each got.

#494 Ship src/ on NPM.
  .npmignore
Labels: DEV

#397 Call fused matMul in core whenever possible for performance.
  src/backend/tfjs_backend.ts
  src/layers/core.ts
Labels: PERF

#501 Update layers to 1.0.2.
  integration_tests/benchmarks/package.json
  integration_tests/benchmarks/yarn.lock
  integration_tests/tfjs2keras/package.json
  integration_tests/tfjs2keras/yarn.lock
  package.json
  src/version.ts
Labels: INTERNAL
