Repository tensorflow/tfjs-layers, pull requests merged in 2019-01, with the labels that each got.

#399 Remove pull request template.
  pull_request_template.md
Labels: INTERNAL

#398 Model.fit(): Push await data() on scalar log values more toward the end
  src/base_callbacks.ts
  src/engine/training_dataset.ts
  src/engine/training_test.ts
Labels: PERF

#434 Change spies to conform with window.fetch API.
  src/models_test.ts
Labels: BUG
